name: provhive
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  provider: ^4.0.4
  path_provider: ^1.6.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.8.0
  hive_generator: ^0.7.0+2
  # flutter_test:
  #   sdk: flutter


flutter:
  uses-material-design: true
